// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IMDB_Website.Models;

[Keyless]
public partial class Actor
{
    [Required]
    [Column("primaryName")]
    [StringLength(150)]
    [Unicode(false)]
    public string PrimaryName { get; set; }

    [Column("deathYear")]
    public short? DeathYear { get; set; }

    [Column("profession")]
    [StringLength(100)]
    [Unicode(false)]
    public string Profession { get; set; }
}