// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IMDB_Website.Models
{
    public partial class findNameResult
    {
        public string nconst { get; set; }
        public string primaryName { get; set; }
        public short? birthYear { get; set; }
        public short? deathYear { get; set; }
    }
}
