// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using IndexAttribute = Microsoft.EntityFrameworkCore.IndexAttribute;

namespace IMDB_Website.Models;

[Index("PrimaryName", Name = "primaryName_index")]
public partial class Name
{
    public Name()
    {
        Directors = new HashSet<Director>();
        KnownForTitles = new HashSet<KnownForTitle>();
        Professions = new HashSet<Profession>();
        Writers = new HashSet<Writer>();
    }

    [Key]
    [Column("nconst")]
    [StringLength(10)]
    [Unicode(false)]
    public string Nconst { get; set; }

    [Required]
    [Column("primaryName")]
    [StringLength(150)]
    [Unicode(false)]
    public string PrimaryName { get; set; }

    [Column("birthYear")]
    public short? BirthYear { get; set; }

    [Column("deathYear")]
    public short? DeathYear { get; set; }

    [InverseProperty("NconstNavigation")]
    public virtual ICollection<Director> Directors { get; set; }

    [InverseProperty("NconstNavigation")]
    public virtual ICollection<KnownForTitle> KnownForTitles { get; set; }

    [InverseProperty("NconstNavigation")]
    public virtual ICollection<Profession> Professions { get; set; }

    [InverseProperty("NconstNavigation")]
    public virtual ICollection<Writer> Writers { get; set; }
}