// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IMDB_Website.Models;

public partial class Profession
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("profession")]
    [StringLength(100)]
    [Unicode(false)]
    public string Profession1 { get; set; }

    [Required]
    [Column("nconst")]
    [StringLength(10)]
    [Unicode(false)]
    public string Nconst { get; set; }

    [ForeignKey("Nconst")]
    [InverseProperty("Professions")]
    public virtual Name NconstNavigation { get; set; }
}